/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as PropertiesSlugApartmentsApartmentIdRouteImport } from './routes/properties.$slug.apartments.$apartmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugApartmentsApartmentIdRoute =
  PropertiesSlugApartmentsApartmentIdRouteImport.update({
    id: '/apartments/$apartmentId',
    path: '/apartments/$apartmentId',
    getParentRoute: () => PropertiesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/properties/$slug': typeof PropertiesSlugRouteWithChildren
  '/properties/$slug/apartments/$apartmentId': typeof PropertiesSlugApartmentsApartmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/properties/$slug': typeof PropertiesSlugRouteWithChildren
  '/properties/$slug/apartments/$apartmentId': typeof PropertiesSlugApartmentsApartmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/properties/$slug': typeof PropertiesSlugRouteWithChildren
  '/properties/$slug/apartments/$apartmentId': typeof PropertiesSlugApartmentsApartmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/properties/$slug'
    | '/properties/$slug/apartments/$apartmentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/properties/$slug' | '/properties/$slug/apartments/$apartmentId'
  id:
    | '__root__'
    | '/'
    | '/properties/$slug'
    | '/properties/$slug/apartments/$apartmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PropertiesSlugRoute: typeof PropertiesSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug/apartments/$apartmentId': {
      id: '/properties/$slug/apartments/$apartmentId'
      path: '/apartments/$apartmentId'
      fullPath: '/properties/$slug/apartments/$apartmentId'
      preLoaderRoute: typeof PropertiesSlugApartmentsApartmentIdRouteImport
      parentRoute: typeof PropertiesSlugRoute
    }
  }
}

interface PropertiesSlugRouteChildren {
  PropertiesSlugApartmentsApartmentIdRoute: typeof PropertiesSlugApartmentsApartmentIdRoute
}

const PropertiesSlugRouteChildren: PropertiesSlugRouteChildren = {
  PropertiesSlugApartmentsApartmentIdRoute:
    PropertiesSlugApartmentsApartmentIdRoute,
}

const PropertiesSlugRouteWithChildren = PropertiesSlugRoute._addFileChildren(
  PropertiesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PropertiesSlugRoute: PropertiesSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
