/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as PropertiesSlugApartmentsApartmentIdRouteImport } from './routes/properties.$slug_.apartments.$apartmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugApartmentsApartmentIdRoute =
  PropertiesSlugApartmentsApartmentIdRouteImport.update({
    id: '/properties/$slug_/apartments/$apartmentId',
    path: '/properties/$slug/apartments/$apartmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/properties/': typeof PropertiesIndexRoute
  '/properties/$slug/apartments/$apartmentId': typeof PropertiesSlugApartmentsApartmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/properties': typeof PropertiesIndexRoute
  '/properties/$slug/apartments/$apartmentId': typeof PropertiesSlugApartmentsApartmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/properties/': typeof PropertiesIndexRoute
  '/properties/$slug_/apartments/$apartmentId': typeof PropertiesSlugApartmentsApartmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/properties/$slug'
    | '/properties/'
    | '/properties/$slug/apartments/$apartmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/properties/$slug'
    | '/properties'
    | '/properties/$slug/apartments/$apartmentId'
  id:
    | '__root__'
    | '/'
    | '/properties/$slug'
    | '/properties/'
    | '/properties/$slug_/apartments/$apartmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  PropertiesSlugApartmentsApartmentIdRoute: typeof PropertiesSlugApartmentsApartmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug_/apartments/$apartmentId': {
      id: '/properties/$slug_/apartments/$apartmentId'
      path: '/properties/$slug/apartments/$apartmentId'
      fullPath: '/properties/$slug/apartments/$apartmentId'
      preLoaderRoute: typeof PropertiesSlugApartmentsApartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  PropertiesSlugApartmentsApartmentIdRoute:
    PropertiesSlugApartmentsApartmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
